<!doctype html>

<head></head>

<body>
  <script>
    class HttpError extends Error {
      constructor(response) {
        super(`${response.status} for ${response.url}`);
        this.name = 'HttpError';
        this.response = response;
      }
    }

    async function loadJson(url) {
      let response = await fetch(url);
          if (response.status == 200) {
            return response.json();
          } else {
            throw new HttpError(response);
          }
    }

    // demander un nom d'utilisateur jusqu'Ã  ce que github renvoie un utilisateur valide
    async function demoGithubUser() {
      let user;

      while(true) {
        let name = prompt("Enter a name?", "iliakan");

        try{
          user =  await loadJson(`https://api.github.com/users/${name}`);
          break;
        } catch(error) {
          if (err instanceof HttpError && err.response.status == 404) {
            alert("No such user, please reenter.");
          } else {
            throw (error);
          }
        }
      }
      alert(`Full name: ${user.name}.`);
      return user;
    }

    demoGithubUser();


  </script>
</body>


</html>